services:
  assetto-server:
    # build:
    #   context: ../
    #   dockerfile: docker/Dockerfile
    # container_name: as
    image: ghcr.io/loopcap/assettoserver:latest
    ports:
      - "9600:9600"
      - "9600:9600/udp"
      - "8081:8081"
    volumes:
      - ./data/:/data
    environment:
      - TZ=Europe/Berlin
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always


